pipeline {
    agent {
        label 'agent-1-label'
    }
    options{
        timeout(time: 50, unit: 'MINUTES')
        disableConcurrentBuilds()
        ansiColor('xterm')
    }
    parameters {
        choice(name: 'ACTION', choices: ['apply', 'destroy'], description: 'Select action')
    }


    stages {
        stage('init') {
            steps {
                withAWS(region: 'us-east-1', credentials: 'aws-cred') {
                    sh """
                        cd 81-cdn
                        terraform init -reconfigure
                    """
                }
            }
        }
        stage('plan') {
            steps {
                withAWS(region: 'us-east-1', credentials: 'aws-cred') {
                    sh """
                        cd 81-cdn
                        terraform plan -out=tfplan
                   """
                }
            }
        }
        stage('apply or destroy') {
            // input {
            //     message "Should we continue to ${params.ACTION}"
            //     ok "Yes,  ${params.ACTION} "
            // }
            steps {
                withAWS(region: 'us-east-1', credentials: 'aws-cred') {
                sh """
                    cd 81-cdn
                    if [ ${params.ACTION} == 'apply' ]
                    then
                        terraform apply -auto-approve tfplan
                    elif [ ${params.ACTION} == 'destroy' ]
                    then
                        terraform destroy -auto-approve
                    fi
                """
                }
            }
        }
        stage('Sequential') {
            when {
                expression { params.ACTION == 'destroy' }
            }
            stages {
                
                stage('ecr') {
                    steps {
                        build job: '71-ecr', parameters: [string(name: 'ACTION', value: "destroy")], wait: true
                    }
                }
                stage('alb-ingress') {
                    steps {
                        build job: '61-ingress-ALB', parameters: [string(name: 'ACTION', value: "destroy")], wait: true
                    }
                }
                stage('acm') {
                    steps {
                        build job: '51-acm', parameters: [string(name: 'ACTION', value: "destroy")], wait: true
                    }
                }
                stage('eks') {
                    steps {
                        build job: '41-eks', parameters: [string(name: 'ACTION', value: "destroy")], wait: true
                    }
                }
                stage('rds') {
                    steps {
                        build job: '31-rds', parameters: [string(name: 'ACTION', value: "destroy")], wait: true
                    }
                }
                stage('bastion') {
                    steps {
                        build job: '21-bastion', parameters: [string(name: 'ACTION', value: "destroy")], wait: true
                    }
                }
                stage('sg') {
                    steps {
                        build job: '11-sg', parameters: [string(name: 'ACTION', value: "destroy")], wait: true
                    }
                }

            }
        }
    }

    post {
        always{
            echo 'this will run always'
            deleteDir()
        }
        success{
            echo 'this will run on success'
        }
        failure{
            echo 'this will run at failure'
        }
    }
}
